POST  http://localhost:3001/api/notes
content-type: application/json 

{   
    "content": "hola a todos",
   "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    
}